# Generated by Django 4.1.7 on 2023-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mall_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "미결제"),
                    ("paid", "결제완료"),
                    ("cancelled", "결제취소"),
                    ("failed", "결제실패"),
                ],
                db_index=True,
                default="ready",
                max_length=9,
            ),
        ),
    ]
